services:
  - docker

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - image=easypi/openvpn-arm
  - docker build -t "$image" -f Dockerfile.arm .
  - docker run --rm "$image" openvpn --version || true
  - docker run --rm "$image" openssl version

after_script:
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push easypi/openvpn-arm
